spring:
  application:
    name: batch-performance-analyzer
  
  # JMX disabled globally
  jmx:
    enabled: false

  # Common JPA Configuration
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 1000
          batch_versioned_data: true
          fetch_size: 1000
        order_inserts: true
        order_updates: true
        cache:
          use_second_level_cache: false

# Common Application Security Settings
app:
  security:
    enabled: ${SECURITY_ENABLED:true}
    admin:
      username: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:}
    viewer:
      username: ${VIEWER_USERNAME:viewer}
      password: ${VIEWER_PASSWORD:}

# Common Performance Configuration
performance:
  test:
    batch-sizes: ${PERF_TEST_BATCH_SIZES:1,10,100,1000,10000}
    metrics:
      collection-interval: ${METRICS_INTERVAL:1000}
      enable-system-metrics: true
      enable-jvm-metrics: true
      enable-database-metrics: true

# Common Server Configuration
server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false
    whitelabel:
      enabled: false

# Common Actuator Configuration
management:
  endpoints:
    web:
      base-path: /actuator
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    health:
      probes:
        enabled: true
    metrics:
      enabled: true
    info:
      enabled: true
  security:
    enabled: true
  prometheus:
    metrics:
      export:
        enabled: ${PROMETHEUS_ENABLED:true}

# Common Logging
logging:
  level:
    org.springframework.jmx: OFF
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"