# Database Batch Performance Analyzer Configuration (JMX-Free)

spring:
  application:
    name: batch-performance-analyzer

  # Completely disable JMX
  jmx:
    enabled: false

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5433/performance_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: PerformanceHikariCP
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      leak-detection-threshold: 60000
      register-mbeans: false  # Disable HikariCP JMX

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 1000
          batch_versioned_data: true
          fetch_size: 1000
        order_inserts: true
        order_updates: true
        generate_statistics: true
        cache:
          use_second_level_cache: false

# Actuator Configuration (Web-based monitoring only)
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all endpoints including prometheus
    jmx:
      exposure:
        exclude: "*"  # Disable all JMX endpoints

  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true

  # Prometheus configuration (Fixed)
  prometheus:
    metrics:
      export:
        enabled: true
        step: PT10S  # Export every 10 seconds for real-time monitoring

  # Metrics configuration
  metrics:
    export:
      prometheus: {}
    distribution:
      percentiles-histogram:
        http.server.requests: true
        jvm.memory.used: true
        jvm.gc.pause: true
        system.cpu.usage: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
      slo:
        http.server.requests: 50ms,100ms,200ms,500ms,1s,2s
    enable:
      jvm: true
      system: true
      process: true
      jdbc: true
      hikaricp: false  # Disable HikariCP JMX metrics

  # Disable InfluxDB
  influx:
    metrics:
      export:
        enabled: false

# Custom Performance Testing Configuration
performance:
  test:
    total-records: 1000000
    batch-sizes: [1, 10, 100, 1000, 10000]
    connection-pool:
      max-size: 20
      min-idle: 5
    metrics:
      collection-interval: 1000
      enable-system-metrics: true
      enable-jvm-metrics: true
      enable-database-metrics: true

# Server Configuration
server:
  port: 8080
  compression:
    enabled: true

# Logging Configuration
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    com.vivek.batchoperationvisulization: DEBUG
    io.micrometer: INFO
    org.springframework.jmx: OFF  # Disable JMX logging
    org.springframework.boot.actuate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"