spring:
  # Docker Database (container names)
  datasource:
    url: jdbc:postgresql://postgres:5432/performance_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: DockerPerformanceHikariCP
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      leak-detection-threshold: 60000
      register-mbeans: false
      connection-test-query: SELECT 1
      validation-timeout: 3000

  # Docker JPA (development-like)
  jpa:
    hibernate:
      ddl-auto: update  # Safe for Docker development
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
        # Add these to suppress session event logging
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: -1

# Docker Rate Limiting (moderate)
app:
  rate-limit:
    enabled: true
    requests-per-minute: 60
    burst-capacity: 20
    performance-operations-per-hour: 50

# Docker Performance Limits
performance:
  test:
    total-records: 10000
    max-records-per-operation: 50000
    max-batch-size: 5000

# Docker Actuator (moderate access)
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      show-details: always

# Docker Logging
logging:
  level:
    com.vivek: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"