# Production Docker Compose Configuration
services:
  app:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: performance-analyzer-prod
    environment:
      # Use Production profile
      - SPRING_PROFILES_ACTIVE=prod
      
      # Required production settings
      - DB_PASSWORD=${DB_PASSWORD}  # MUST be provided
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}  # MUST be provided
      - VIEWER_PASSWORD=${VIEWER_PASSWORD}  # MUST be provided
      
      # Production database settings
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=performance_db
      - DB_USERNAME=postgres
      - DB_SSL_ENABLED=${DB_SSL_ENABLED:-false}
      
      # Production monitoring
      - PROMETHEUS_ENABLED=true
      
    ports:
      - "8080:8080"
    volumes:
      - app_logs:/app/logs
      - app_data:/app/data
    networks:
      - performance-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: '1.0'
        reservations:
          memory: 1g
          cpus: '0.5'

  postgres:
    image: postgres:16-alpine
    container_name: performance-postgres-prod
    environment:
      POSTGRES_DB: performance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backups:/backups
      - ./init-db.sql:/docker-entrypoint-initdb.d/01-init-db.sql:ro
      - ./init-performance-tables.sql:/docker-entrypoint-initdb.d/02-init-performance-tables.sql:ro
    networks:
      - performance-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d performance_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '0.5'

  prometheus:
    image: prom/prometheus:v2.48.0
    container_name: performance-prometheus-prod
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus-prod.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alerts-prod.yml:/etc/prometheus/alerts.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
    networks:
      - performance-network
    depends_on:
      - app
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.2.0
    container_name: performance-grafana-prod
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ALLOW_EMBEDDING=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    networks:
      - performance-network
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  postgres_data:
  postgres_backups:
  prometheus_data:
  grafana_data:
  app_logs:
  app_data:

networks:
  performance-network:
    driver: bridge