# Basic Alert Rules Configuration
# Save this as: Docker/prometheus/alerts.yml

groups:
  - name: application.rules
    rules:
      # Application Health Alerts
      - alert: ApplicationDown
        expr: up{job="batch-performance-analyzer"} == 0
        for: 1m
        labels:
          severity: critical
          component: application
        annotations:
          summary: "Application is down"
          description: "Batch Performance Analyzer application has been down for more than 1 minute"

      # High Memory Usage Alert
      - alert: HighMemoryUsage
        expr: jvm_memory_heap_usage_percent > 85
        for: 3m
        labels:
          severity: warning
          component: jvm
        annotations:
          summary: "High JVM memory usage"
          description: "JVM heap usage is {{ $value }}% (threshold: 85%)"

      # HTTP Error Rate Alert
      - alert: HighHttpErrorRate
        expr: rate(http_server_requests_seconds_count{status=~"5.."}[5m]) / rate(http_server_requests_seconds_count[5m]) > 0.05
        for: 3m
        labels:
          severity: warning
          component: http
        annotations:
          summary: "High HTTP error rate"
          description: "HTTP 5xx error rate is {{ $value }} (threshold: 0.05 or 5%)"
