global:
  smtp_smarthost: localhost:587
  smtp_from: alerts@company.com

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'null-receiver'

receivers:
- name: 'null-receiver'

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'dev', 'instance']
