# Fixed Prometheus Configuration
# Save this as: Docker/prometheus/prometheus.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "batch-performance-monitor"

# FIXED: Proper AlertManager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "alerts.yml"

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 30s

  # Spring Boot Application (Main target)
  - job_name: "batch-performance-analyzer"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    scrape_timeout: 4s
    static_configs:
      - targets: ["app:8080"] # Docker service name
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: app:8080

  # PostgreSQL Database Metrics (if postgres_exporter is added)
  - job_name: "postgresql"
    static_configs:
      - targets: ["postgres:5432"]
    scrape_interval: 30s
    metrics_path: "/metrics"
    # Note: Requires postgres_exporter sidecar container

  # Redis Metrics (if redis_exporter is added)
  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    scrape_interval: 30s
    metrics_path: "/metrics"
    # Note: Requires redis_exporter sidecar container
